server:
  port: 20000
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  elasticsearch:
    rest:
      uris: 192.168.17.131:9200
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: 192.168.17.131
    virtual-host: /yxl
    username: yxl
    password: yxl
    listener:
      simple:
        prefetch: 1
        #消费者确认：手动模式
        acknowledge-mode: manual

  redis:
    host: 192.168.17.131
    port: 16379
feign:
  sentinel:
    enabled: true
