server:
  port: 10884
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web
    discovery-client-enabled: false
  sleuth:
    sampler:
      probability: 1
  datasource:
    url: jdbc:mysql://192.168.17.131:3307/guli_wms
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  redis:
    port: 16379
    host: 192.168.17.131
  rabbitmq:
    host: 192.168.17.131
    virtual-host: /yxl
    username: yxl
    password: yxl
    listener:
      simple:
        acknowledge-mode: manual
feign:
  sentinel:
    enabled: true
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
